FROM mariadb:10.4
MAINTAINER sdm "sdm2345@163.com"
# mariadb-rocksdb-tokudb-docker
#RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g'  /etc/apt/sources.list && \

RUN apt-get update && \
    apt-get install mariadb-plugin-rocksdb -y